projects:
  default:
    schema: schema.graphql
    documents: graphql/test/**.graphql
    extensions:
      turms:
        out_dir: tests/apis
        generated_name: tests.py
        stylers:
          - type: turms.stylers.default.DefaultStyler
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operations.OperationsPlugin
          - type: turms.plugins.funcs.FuncsPlugin
            global_kwargs:
              - key: rath
                type: rath.rath.Rath
                description: The rath client to execute the operation on
            definitions:
              - type: query
                use: rath.turms.funcs.execute
              - type: mutation
                use: rath.turms.funcs.execute
              - type: subscription
                use: rath.turms.funcs.subscribe
              - type: query
                is_async: true
                use: rath.turms.funcs.aexecute
              - type: mutation
                is_async: true
                use: rath.turms.funcs.aexecute
              - type: subscription
                is_async: true
                use: rath.turms.funcs.asubscribe
        processors:
          - type: turms.processors.black.BlackProcessor
        scalar_definitions:
          uuid: str
  countries:
    schema: https://countries.trevorblades.com/
    documents: graphql/countries/**.graphql
    extensions:
      turms:
        out_dir: tests/apis/
        generated_name: countries.py
        stylers:
          - type: turms.stylers.default.DefaultStyler
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operations.OperationsPlugin
          - type: turms.plugins.funcs.FuncsPlugin
            global_kwargs:
              - key: rath
                type: rath.rath.Rath
                description: The rath client to execute the operation on
            definitions:
              - type: query
                use: rath.turms.funcs.execute
              - type: mutation
                use: rath.turms.funcs.execute
              - type: subscription
                use: rath.turms.funcs.subscribe
              - type: query
                is_async: true
                use: rath.turms.funcs.aexecute
              - type: mutation
                is_async: true
                use: rath.turms.funcs.aexecute
              - type: subscription
                is_async: true
                use: rath.turms.funcs.asubscribe
        processors:
          - type: turms.processors.black.BlackProcessor
        scalar_definitions:
          uuid: str
  nested_inputs:
    schema: tests/schemas/nested_inputs.graphql
    documents: tests/documents/nested_inputs/*.graphql
    extensions:
      turms:
        out_dir: tests/apis
        generated_name: nested_inputs.py
        stylers:
          - type: turms.stylers.default.DefaultStyler
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operations.OperationsPlugin
          - type: turms.plugins.funcs.FuncsPlugin
            global_kwargs:
              - key: rath
                type: rath.rath.Rath
                description: The rath client to execute the operation on
            definitions:
              - type: query
                use: rath.turms.funcs.execute
              - type: mutation
                use: rath.turms.funcs.execute
              - type: subscription
                use: rath.turms.funcs.subscribe
              - type: query
                is_async: true
                use: rath.turms.funcs.aexecute
              - type: mutation
                is_async: true
                use: rath.turms.funcs.aexecute
              - type: subscription
                is_async: true
                use: rath.turms.funcs.asubscribe
        processors:
          - type: turms.processors.black.BlackProcessor
          - type: turms.processors.isort.IsortProcessor
        scalar_definitions:
          uuid: str
          timestamptz: str
          Date: str
